### ISSUE TITLE
README.md 標題似乎有誤

### ISSUE THREAD

**Issue by Korver2017** [newming/vuepress#1]
您的 `README.md` 大標題是 **玩转 vu `r` Press**
不太確定您原本想寫的是 **玩转 vu `e` Press** 嗎？
不好意思，無意冒犯說不定是我會錯意 : )

**Comment by newming** [comment]
抱歉，是标题存在问题，仅仅只是一个vuepress demo

**Comment by Korver2017** [comment]
感謝你的回覆
也感謝你的無私分享 : )
